# Generated by Django 4.2.5 on 2023-11-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommerceuser',
            name='password',
        ),
    ]
